# Arquivo: application.yml

server:
  servlet:
    context-path: /api/v1.0

spring:
  application:
    name: final_project
    
  datasource:
    url: jdbc:mysql://localhost:3306/meu_projeto_db
    username: root
    password: root # Cuidado ao enviar senhas para o Git!
    
  jpa:
    hibernate:
      ddl-auto: update